[package]
name = "busycityguy/stateq"
description = "An intuitive fully-typed Finite State Machine in Luau that supports async transitions by queueing events"
version = "0.0.2"
license = "MIT"
authors = ["BusyCityGuy"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["*"]
include = [
    "src/StateQ",
    "src/StateQ/**",
    "default.project.json",
    "wally.toml",
    "README.md",
    "LICENSE.md",
]

[dependencies]
t = "osyrisrblx/t@3.0.0"

[dev-dependencies]
Freeze = "duckarmor/freeze@0.1.4"
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
