[package]
name = "busycityguy/stateq"
description = "An intuitive fully-typed Finite State Machine in Luau that supports async transitions by queueing events"
version = "0.0.7"
license = "MIT"
authors = ["BusyCityGuy"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["*"]
include = [
    "src",
    "src/StateQ",
    "src/StateQ/**",
    "default.project.json",
    "wally.toml",
    "README.md",
    "LICENSE.md",
]

[dependencies]
t = "corecii/greentea-t-standalone@0.4.7"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
