[package]
name = "busycityguy/finite-state-machine-luau"
description = "A feature rich and fully typed implementation of a Finite State Machine in Luau, developed for use in Roblox experiences"
version = "0.1.0"
license = "MIT"
authors = ["BusyCityGuy"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
t = "corecii/greentea-t-standalone@0.4.7"

[dev-dependencies]
Freeze = "duckarmor/freeze@0.1.4"
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
